
# Build the react app 
FROM node:24-alpine AS build
WORKDIR /app

# Copy dependeny and install
COPY package*.json ./
RUN npm install

# Copy soure and build
COPY . .
RUN npm run build
 
 FROM nginx:1.28-alpine
 COPY --from=build /app/dist/ /usr/share/nginx/html 
 EXPOSE 80
 CMD [ "nginx", "-g", "daemon off;" ]