name: driving-lesson-project
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy spring boot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build the application
        run: |
          mvn clean
          mvn -B package
        working-directory: ./backend 